inherit_from: .rubocop_todo.yml

require: rubocop-performance

AllCops:
  DisplayCopNames: true
  Exclude:
    - 'gemfiles/**/*'
    - 'vendor/**/*'
  NewCops: enable
  TargetRubyVersion: 2.5

Metrics/LineLength:
  IgnoreCopDirectives: true
  Max: 120

Naming/FileName:
  Exclude:
    - 'Appraisals'

Naming/VariableNumber:
  EnforcedStyle: snake_case

