name: Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        ruby: ['2.5', '2.6', '2.7', '3.0']
        gemfile: ['active6.0.3.6', 'active6.1.3.1', 'rails6.0.3.6', 'rails6.1.3.1']
        include:
          - ruby: 2.5
            gemfile: active5.2.5
          - ruby: 2.6
            gemfile: active5.2.5
          - ruby: 2.7
            gemfile: active5.2.5
          - ruby: 2.5
            gemfile: rails5.2.5
          - ruby: 2.6
            gemfile: rails5.2.5
          - ruby: 2.7
            gemfile: rails5.2.5
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
    services:
      mongodb:
        image: mongo:4.4.10
        ports:
          - 8081:8081
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rubocop -P
      - run: bundle exec rspec -f d spec
