name: Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        ruby: ['3.0', '3.1', '3.2', '3.3']
        gemfile: ['active6.0.6', 'active6.1.7.6', 'active7.0.8', 'active7.1.3', 'rails6.0.6', 'rails6.1.7.6', 'rails7.0.8', 'rails7.1.3']
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
      RUBY_OPT: --disable=did_you_mean
    services:
      mongodb:
        image: mongo:4.4.10
        ports:
          - 8081:8081
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          cache-version: 1
      - run: bundle install --jobs 2 --retry 3
      - run: bundle exec rubocop -P
      - run: bundle exec rspec -f d spec
